ENV['RCT_NEW_ARCH_ENABLED'] = '0'

require Pod::Executable.execute_command(
  'node',
  ['-p',
   'require.resolve(
      "react-native/scripts/react_native_pods.rb",
      {paths: [process.argv[1]]},
    )',
   __dir__
  ]
).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

use_frameworks! :linkage => :static

pre_install do |installer|
  installer.pod_targets.each do |pod|
    if pod.name == 'hermes-engine'
      def pod.build_type
        Pod::BuildType.static_library
      end
    end
  end
end

target '어바웃' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false,
    :fabric_enabled => false,
    :new_arch_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'FirebaseCore'
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'

  target '어바웃Tests' do
    inherit! :complete
  end
end

post_install do |installer|
  react_native_post_install(
    installer,
    (use_native_modules![:reactNativePath]),
    :mac_catalyst_enabled => false
  )

  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |c|
      c.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
